### ISSUE TITLE
20230316 CrossCompute.com Not Secure

### ISSUE THREAD

**Issue by kashfifahim** [crosscompute/crosscompute-homepage#24]
Trying to access CrossCompute.com, Chrome blocks access.

> www.crosscompute.com normally uses encryption to protect your information. When Chrome tried to connect to www.crosscompute.com this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be www.crosscompute.com, or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Chrome stopped the connection before any data was exchanged.
> 
> You cannot visit www.crosscompute.com right now because the website uses HSTS. Network errors and attacks are usually temporary, so this page will probably work later.

**Comment by invisibleroads** [comment]
Thanks so much for the issue. Will fix in a bit

**Comment by invisibleroads** [comment]
Fixed -- we should set up monitoring one day
